"""empty message

Revision ID: daf09a0c346a
Revises: 
Create Date: 2021-05-21 02:09:53.850703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf09a0c346a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('secret_key'),
    sa.UniqueConstraint('secret_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
